[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
hdi = "0.3.4"
hdk = "0.2.4"
serde = "1"
holochain = { version = "0.2.4", default-features = false, features = [
  "test_utils",
] }
[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
