[workspace]
members = ["crates/*", "tests"]
resolver = "2"

[workspace.dependencies]
hdi = "0.3"
hdk = "0.2"
serde = "1"
holochain = "0.3.0-beta-dev.8"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
